[package]
name = "ort_example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
ort = {version = "=2.0.0-rc.10", features=["cuda", "load-dynamic"]}
ort-sys = {version = "=2.0.0-rc.10"}
